/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental.motor;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wahaz
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        selectedData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtStruk = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDateChooserP = new com.toedter.calendar.JDateChooser();
        jDateChooserK = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        txtNoPol = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtNama);
        txtNama.setBounds(110, 140, 150, 30);
        getContentPane().add(txtAlamat);
        txtAlamat.setBounds(110, 180, 150, 30);
        getContentPane().add(txtStruk);
        txtStruk.setBounds(370, 140, 150, 30);

        harga.setText("Rp20000/Hari");
        harga.setEnabled(false);
        getContentPane().add(harga);
        harga.setBounds(650, 220, 150, 30);

        jLabel1.setText("Harga");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 220, 100, 30);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 140, 100, 30);

        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 180, 100, 30);

        jLabel4.setText("No Struk");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 140, 100, 30);

        jLabel5.setText("No Polisi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 180, 100, 30);

        jLabel6.setText("Tanggal Pinjam");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 140, 100, 30);

        jLabel7.setText("Tanggal Kembali");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(550, 180, 100, 30);
        getContentPane().add(jDateChooserP);
        jDateChooserP.setBounds(650, 140, 150, 30);
        getContentPane().add(jDateChooserK);
        jDateChooserK.setBounds(650, 180, 150, 30);

        jLabel9.setFont(new java.awt.Font("Market Deco", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("RENTAL MOTOR ABADI JAYA");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(310, 30, 350, 50);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint);
        btnPrint.setBounds(400, 230, 73, 30);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(100, 230, 73, 30);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(200, 230, 73, 30);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Nama", "Alamat", "No Struk", "No Polisi", "Tgl Pinjam", "Tgl Kembali", "Harga"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 270, 700, 240);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(300, 230, 73, 30);
        getContentPane().add(txtNoPol);
        txtNoPol.setBounds(370, 180, 150, 30);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Form Rental Sepeda Motor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Exo 2", 0, 14))); // NOI18N
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 100, 860, 440);

        jPanel2.setBackground(new java.awt.Color(43, 101, 248));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 860, 110);

        setSize(new java.awt.Dimension(875, 569));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Rekapitulasi Rental Motor Abadi Jaya");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)   ");
        
        try{
            tblData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch(java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggalP = dateFormat.format(jDateChooserP.getDate());
        String tanggalK = dateFormat.format(jDateChooserK.getDate());

        Date date1 = jDateChooserP.getDate();
        Date date2 = jDateChooserK.getDate(); 
        long differenceInMilliseconds = date2.getTime() - date1.getTime();
        int differenceInDays = (int)differenceInMilliseconds/(1000*60*60*24);
        Integer hargatotal = differenceInDays*20000;
        
        if(txtNama.getText().equals("")||txtAlamat.getText().equals("")||txtStruk.getText().equals("")||txtNoPol.getText().equals("")||jDateChooserP.getDate().equals("")||jDateChooserK.getDate().equals("")){
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }else {
            String SQL = "INSERT INTO tb_rental(nama,alamat,no_struk,no_pol,tgl_pinjam,tgl_kembali,harga)"
                    +"VALUES('"+txtNama.getText()+"','"+txtAlamat.getText()+"','"+txtStruk.getText()+"','"+harga.getText()+"','"+tanggalP+"',"
                    +"'"+tanggalK+"','"+hargatotal+"')";
            
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectedData();
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtAlamat.setText("");
        txtStruk.setText("");
        jDateChooserP.setDate(null);
        jDateChooserK.setDate(null);
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tblData.getSelectedRow();
        if(baris != -1){
            String id = tblData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_rental WHERE id='"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if(status==1){
                JOptionPane.showMessageDialog(this,"Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectedData();
            } else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField harga;
    private com.toedter.calendar.JDateChooser jDateChooserK;
    private com.toedter.calendar.JDateChooser jDateChooserP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblData;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoPol;
    private javax.swing.JTextField txtStruk;
    // End of variables declaration//GEN-END:variables

     private void selectedData() {
        String kolom[] = {"id","nama","alamat","no_struk","no_pol","tgl_pinjam","tgl_kembali","harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT `id`,`nama`, `alamat`, `no_struk`, `no_pol`, `tgl_pinjam`, `tgl_kembali`, `harga` FROM `tb_rental`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String id = rs.getString(1);
                String nama = rs.getString(2);
                String alamat = rs.getString(3);
                String no_struk = rs.getString(4);
                String no_pol = rs.getString(5);
                String tgl_pinjam = rs.getString(6);
                String tgl_kembali = rs.getString(7);
                String harga = rs.getString(8);
                String data[] = {id,nama,alamat,no_struk,no_pol,tgl_pinjam,tgl_kembali,harga};
                dtm.addRow(data);
                
            }
        } catch (SQLException ex){
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
        }
        tblData.setModel(dtm);
    }
}
